import type { Product } from "@/types";

export const NAV_LINKS = [
  { label: "Flavors", href: "#products" },
  { label: "How It Works", href: "#how" },
  { label: "Our Story", href: "#story" },
  { label: "Order", href: "#order" },
];

export const PLACEHOLDER_IMAGE = "/images/placeholder-loaf.svg";

/** Fallback products when Supabase is unavailable */
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "classic",
    name: "Classic Chocolate Chip",
    slug: "classic",
    priceCents: 3500,
    wholesalePriceCents: 2500,
    calories: 290,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat"],
    description: "Our original protein-packed banana bread with premium chocolate chips.",
    image: "/images/loaves/classic_1.png",
    accentColor: "#E8B44C",
    stripeColor: "#E8B44C",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "coconut-walnut",
    name: "Coconut Walnut Chocolate Chip",
    slug: "coconut-walnut",
    priceCents: 3800,
    wholesalePriceCents: 2800,
    calories: 350,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat", "Tree Nuts", "Coconut"],
    description: "Toasted coconut and walnuts with chocolate chips for a tropical twist.",
    image: "/images/loaves/coconut-walnut_1.png",
    accentColor: "#E8B44C",
    stripeColor: "#E8B44C",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 2,
    isBestSeller: true,
  },
  {
    id: "double-chocolate",
    name: "Double Chocolate Chocolate Chip",
    slug: "double-chocolate",
    priceCents: 3800,
    wholesalePriceCents: 2800,
    calories: 330,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat"],
    description: "Rich cocoa banana bread loaded with chocolate chips for the ultimate chocolate lover.",
    image: "/images/loaves/double-chocolate_1.png",
    accentColor: "#4A3428",
    stripeColor: "#4A3428",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 3,
    isBestSeller: true,
  },
  {
    id: "blueberry",
    name: "Blueberry Chocolate Chip",
    slug: "blueberry",
    priceCents: 3500,
    wholesalePriceCents: 2600,
    calories: 320,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat"],
    description: "Dried blueberries meet rich chocolate chips in our most popular flavor.",
    image: "/images/loaves/blueberry_1.png",
    accentColor: "#8FA882",
    stripeColor: "#8FA882",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "walnut",
    name: "Walnut Chocolate Chip",
    slug: "walnut",
    priceCents: 3500,
    wholesalePriceCents: 2600,
    calories: 340,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat", "Tree Nuts"],
    description: "Crunchy walnuts paired with chocolate chips for the ultimate texture.",
    image: "/images/loaves/walnut_1.png",
    accentColor: "#C8703E",
    stripeColor: "#C8703E",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "raspberry-white-choc",
    name: "Raspberry White Chocolate",
    slug: "raspberry-white-choc",
    priceCents: 3800,
    wholesalePriceCents: 2800,
    calories: 310,
    proteinGrams: 12,
    allergens: ["Milk", "Eggs", "Wheat"],
    description: "Tart raspberries swirled with creamy white chocolate for a bright, indulgent loaf.",
    image: "/images/loaves/raspberry-white-choc_1.jpeg",
    accentColor: "#C85A7C",
    stripeColor: "#C85A7C",
    inventoryRemaining: null,
    isActive: true,
    sortOrder: 6,
  },
];

export const CONTACT = {
  email: "zack@brekkiebakery.com",
  address: "Brekkie LLC, 1580 Park Ave, New York, NY 10029",
  instagram: "https://instagram.com/brekkiebakery",
};

export const BUSINESS_TYPES = [
  "Bodega",
  "Cafe",
  "Gym",
  "Office",
  "Restaurant",
  "Other",
];

export const FREQUENCIES = [
  { value: "one-time", label: "One-time" },
  { value: "weekly", label: "Weekly" },
  { value: "biweekly", label: "Biweekly" },
  { value: "monthly", label: "Monthly" },
];
